<?php 
 return [ 'name'=>'Nautilus',
'components' =>['mailer' =>['class'=>'common\components\Mailer',
'viewPath'=>'@common/mail',
],
'settings' =>['class'=>'yii2mod\settings\components\Settings',
],
'db' =>['class'=>'yii\db\Connection',
'dsn'=>'mysql:host=localhost; port=3306;dbname=julian',
'username'=>'tomasito',
'password'=>'tomasito',
'charset'=>'utf8',
'tablePrefix'=>'8nurj_',
],
],
'language'=>'es_PE',
];  ?>